## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('applications', ['internet', 'config-store','stats'])
    module.use.append('DASH')
    module.source = [
        'model/bulk-send-application.cc',
        'model/onoff-application.cc',
        'model/packet-sink.cc',
        'model/udp-client.cc',
        'model/udp-server.cc',
        'model/seq-ts-header.cc',
        'model/udp-trace-client.cc',
        'model/packet-loss-counter.cc',
        'model/udp-echo-client.cc',
        'model/udp-echo-server.cc',
        'model/v4ping.cc',
        'model/mp-tcp-packet-sink.cc',
        'model/mp-tcp-bulk-send-application.cc',
        'helper/mp-tcp-packet-sink-helper.cc',
        'helper/mp-tcp-bulk-send-helper.cc',
        'model/application-packet-probe.cc',
        'model/dash-fake-server.cc',
        'model/http-server.cc',
        'model/node-throughput-tracer.cc',
        'model/http-server-fake-clientsocket.cc',
        'model/http-server-fake-virtual-clientsocket.cc',
        'model/http-client.cc',
        'model/http-multimedia-consumer.cc',
        'model/dashplayer-tracer.cc',
        'helper/bulk-send-helper.cc',
        'helper/on-off-helper.cc',
        'helper/packet-sink-helper.cc',
        'helper/udp-client-server-helper.cc',
        'helper/udp-echo-helper.cc',
        'helper/v4ping-helper.cc',
        'helper/http-helper.cc',
        'helper/dash-http-client-helper.cc',
        'helper/dash-server-helper.cc'
        ]

    applications_test = bld.create_ns3_module_test_library('applications')
    applications_test.source = [
        'test/udp-client-server-test.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'applications'
    headers.source = [
        'model/bulk-send-application.h',
        'model/onoff-application.h',
        'model/packet-sink.h',
        'model/udp-client.h',
        'model/udp-server.h',
        'model/seq-ts-header.h',
        'model/udp-trace-client.h',
        'model/packet-loss-counter.h',
        'model/udp-echo-client.h',
        'model/udp-echo-server.h',
        'model/v4ping.h',
        'helper/mp-tcp-packet-sink-helper.h',
        'helper/mp-tcp-bulk-send-helper.h',
        'model/mp-tcp-packet-sink.h',
        'model/mp-tcp-bulk-send-application.h',
        'model/application-packet-probe.h',
        'model/dash-fake-server.h',
        'model/http-server.h',
        'model/node-throughput-tracer.h',
        'model/http-server-fake-clientsocket.h',
        'model/http-server-fake-virtual-clientsocket.h',
        'model/http-client.h',
        'model/http-multimedia-consumer.h',
        'model/dashplayer-tracer.h',
        'helper/bulk-send-helper.h',
        'helper/on-off-helper.h',
        'helper/packet-sink-helper.h',
        'helper/udp-client-server-helper.h',
        'helper/udp-echo-helper.h',
        'helper/v4ping-helper.h',
        'helper/http-helper.h',
        'helper/dash-http-client-helper.h',
        'helper/dash-server-helper.h',
        ]

    bld.ns3_python_bindings()
